$(function(){
    $("#show").click(function(){
        $(".box").show(1000)
    })
    $("#hide").click(function(){
        $(".box").hide(1000)
    })
    $("#showhide").click(function(){
        $(".box").toggle(1000)
    })
})
